# Generated by Django 2.2.3 on 2019-07-06 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order_manager', '0004_shops_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='shop_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='order_manager.Shops'),
            preserve_default=False,
        ),
    ]
