# Generated by Django 2.2.3 on 2019-07-06 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_manager', '0008_auto_20190706_1709'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='client_phone',
        ),
        migrations.AddField(
            model_name='client',
            name='phone',
            field=models.CharField(default=6875776579, max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
