# Generated by Django 2.2.3 on 2019-07-06 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_manager', '0009_auto_20190706_1714'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='branch',
        ),
    ]
