# Generated by Django 2.2.3 on 2019-07-07 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order_manager', '0010_remove_client_branch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordertemplate',
            name='item_id',
        ),
        migrations.RemoveField(
            model_name='ordertemplate',
            name='quantity',
        ),
        migrations.CreateModel(
            name='OrderItemStack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order_manager.Items')),
                ('order_temp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order_manager.OrderTemplate')),
            ],
        ),
    ]
