# Generated by Django 2.2.3 on 2019-07-08 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_manager', '0011_auto_20190707_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='morning_time',
            field=models.TimeField(),
        ),
    ]
