# Generated by Django 2.2.3 on 2019-07-08 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_manager', '0012_auto_20190708_1257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='phone',
        ),
    ]
