# Generated by Django 2.2.3 on 2019-07-08 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_manager', '0013_remove_schedule_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Automate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_at_times', models.TimeField()),
            ],
        ),
    ]
