# Generated by Django 2.2.3 on 2019-07-08 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_manager', '0014_automate'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='address',
            field=models.CharField(default='qwerty', max_length=300),
            preserve_default=False,
        ),
    ]
