# Generated by Django 2.2.3 on 2019-07-09 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_manager', '0017_auto_20190709_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_temp_id',
            field=models.IntegerField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.IntegerField(default=False),
        ),
    ]
