# Generated by Django 2.2.3 on 2019-07-09 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_manager', '0018_auto_20190709_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_temp_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='evening_schedule',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='morning_schedule',
            field=models.BooleanField(default=False),
        ),
    ]
