# Generated by Django 2.2.3 on 2019-07-10 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_manager', '0019_auto_20190709_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlist',
            name='price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='schedule',
            name='evening_time',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='morning_time',
            field=models.TimeField(blank=True),
        ),
    ]
